apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: random-champion
spec:
  replicas: 5
  selector:
    matchLabels:
      app: random-champion
  template:
    metadata:
      labels:
        app: random-champion
    spec:
      containers:
        - name: random-champion
          image: fjbarrena/random-champion:latest
          ports:
            - name: http
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: random-champion
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: random-champion
  type: LoadBalancer
